/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MaximumCostLaptopCount;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

public class App {

  public static void main(String[] args) {
    Scanner sc = new Scanner(System.in);
    System.out.println("================================");
    for (int i = 0; i < 3; i++) {
      String s1 = sc.next();
      int x = sc.nextInt();
      System.out.printf("%-14s %03d\n", s1, x);
    }
    System.out.println("================================");
  }

  public static int maxCost(List<Integer> cost, List<String> labels, int dailyCount) {
    int maxCost = 0;
    int dailyProd = 0;
    int dailyCost = 0;
    for (int i = 0; i < cost.size(); i++) {
      if (dailyProd == dailyCount) {
        if (dailyCost > maxCost)
          maxCost = dailyCost;
        dailyCost = 0;
        dailyProd = 0;
      }
      dailyCost += cost.get(i);
      if ("legal".equals(labels.get(i)))
        dailyProd++;
    }
    return maxCost;
  }
}
