/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MaximumCostLaptopCount;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.List;

class AppTest {
 
  @Test
  void shouldReturn5() {
    List<Integer> cost = Arrays.asList(0, 3, 2, 3, 4);
    List<String> labels = Arrays.asList("legal", "legal", "illegal", "legal", "legal");
    int dailyCount = 1;

    var result = App.maxCost(cost, labels, dailyCount);

    assertEquals(5, result);
  }

  @Test
  void shouldReturn11() {
    List<Integer> cost = Arrays.asList(3,2,0,2,4,0,1,4);
    List<String> labels = Arrays.asList("legal","illegal","legal","legal","illegal","legal","legal","legal");
    int dailyCount = 4;

    var result = App.maxCost(cost, labels, dailyCount);

    assertEquals(11, result);
  }
}
